### PR TITLE
Add intances of the Storable class.

### PR DESCRIPTION
**Pull request by rabipelais**
This addresses issue #14.
I am not very experienced with TH, but this compiles and seems to do the Right Thing when I tested it on a side project.
Do you have any guidelines to contributing, regarding for example code style?

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Thanks for your contribution.

Unfortunately, as Travis indicates, [your PR fails to compile with GHC 7.8 and 7.10](https://travis-ci.org/nikita-volkov/record/builds/53705542). So I can't merge it until the issue is fixed.

**Comment by rabipelais** [comment]
Is there a way to view a detailed error message? Because I suspect the issue is a timeout when compiling.

**Comment by nikita-volkov** [comment]
You may be right, since this project requires long compilation times, however 10 minutes seems just too long. Usually it is an indication of an infinite loop during compilation, and since we're dealing with compile-time macros here, chances are, it is the case.

**Comment by rabipelais** [comment]
The log for 7.8 says it compiles correctly, but timesout on the `Test suite doctest: RUNNING...`, could this be because of my changes? (I didn't touch the doctest `Main.hs` nor any doctest comments.)
It does pass the other 7.8 build, the one without `lower_bound_dependencies=1`, although both compile correctly. I find this all really weird.

As for the 7.10 build, they made some changes to the TH API, and I am working on it.

**Comment by nikita-volkov** [comment]
Oh. You're right. 

It actually failed on both executions on 7.8 the first time, but then I relaunched the build and one of them just passed fine. I've relaunched the other one again just now - we'll see how it'll go. Probably there is no issue with 7.8 compatibility and it merely takes doctest too long to run.

**Comment by nikita-volkov** [comment]
I've updated the Travis configuration to extend the 10 minute timeout. We'll see whether the commit https://github.com/nikita-volkov/record/commit/aa594e5ea9e63bdad116404b12994a4aace8bdad fixes the issues for 7.8.

**Comment by rabipelais** [comment]
Thank you! More time seemed to solve the issue! I still find weird that the new build, with the extra time, took less time than the previous one, and would therefore not need the extra time....

I will try to solve the issue with 7.10

**Comment by rabipelais** [comment]
It should work now (compiles locally), but for 7.10 Travis complains with the error `cabal: Prelude.chr: bad argument` as referenced in [this](https://github.com/haskell/cabal/issues/2251) cabal bug. I see you commented there, how did you manage to solve it?

(Also, I don't know if this pull request is taking into account the commit aa594e5 where you solved the timeout issue. What would be proper here? For me to merge `pr/15` into this pull request? However, note that the Travis builds passed.)

**Comment by nikita-volkov** [comment]
It's merged and released now as 0.2.2. Thanks again for your contribution and for being responsible.

> Travis complains with the error cabal: Prelude.chr: bad argument as referenced in this cabal bug. I see you commented there, how did you manage to solve it?

I didn't manage to solve it. That bug is the sole reason why failures are allowed for the 7.10 build target.

**Comment by nikita-volkov** [comment]
Oops. I forgot that I had some unreleased API-changing updates on master. So a proper version for this is 0.3.0.

**Comment by rabipelais** [comment]
Thanks for merging! And for the hard work you put on this library. Shame about the cabal bug.

**Pull request merged**
