### PR TITLE
Parser should be able to parse arrow types.

### PR DESCRIPTION
**Pull request by rabipelais**
This addresses issue #10, but still doesn't allow lambda syntax.
Declaring something like `type Foo = [r| {foo :: String -> String} |]` works, though.

### CODE REVIEW

**Comment by rabipelais** [comment]
@nikita-volkov How are you doing with that parser reimplementation you mentioned?

**Comment by nikita-volkov** [comment]
Sorry I just got home and am too tired to review. I'll get back to this tomorrow.

> How are you doing with that parser reimplementation you mentioned?

Quite good actually. It's almost finished. All that's left to implement is some workarounds so that compiler error-reports would refer to proper locations in code. I've published my development branch ("preprocessor/main"). To see the preprocessor in action look at the "preprocessor/Main.hs" executable.

**Comment by nikita-volkov** [comment]
Released in 0.3.1. Thanks

**Comment by rabipelais** [comment]
Cool, thank you, although this will be useless when you release you new super-uber-parser :P 
I will take a look at the preprocessor branch and play with it.

**Pull request merged**
